### ISSUE TITLE
SPDY / HTTP2 Support

### ISSUE THREAD

**Issue by derekperkins** [scottcorgan/pushstate-server#12]
When developing locally using pushstate-server, I usually end up loading way more small individual assets, which takes a long time to load. If this supported SPDY / HTTP2, every refresh (of which there are many) should speed up significantly. 

I understand that this isn't necessarily a production ready server and obviously isn't a dealbreaker, but it would save a lot of devs a lot of waiting. @tannerlinsley

**Comment by scottcorgan** [comment]
Seems to be something outside the specs of this module. Maybe a new module. Would be better.

I'll close this for now. Are you up to creating it?
