### ISSUE TITLE
less extension

### ISSUE THREAD

**Issue by cskevint** [scottcorgan/pushstate-server#15]
What do you think about adding the less extension to the statically served assets? Using the less.js browser library, you can include less files in link rel without needing to compile to css.

**Comment by scottcorgan** [comment]
A PR would be great for this. Any you submit one?

**Comment by cskevint** [comment]
https://github.com/scottcorgan/pushstate-server/pull/16

**Comment by scottcorgan** [comment]
Fixed in https://github.com/scottcorgan/pushstate-server/commit/395b03d729a2ab6900950bd9706af42d92149197
