### ISSUE TITLE
Any idea, How to use LiveReload along with pushStateServer ?

### ISSUE THREAD

**Issue by nsisodiya** [scottcorgan/pushstate-server#17]

**Comment by scottcorgan** [comment]
That seems to be out of the scope of this module. For something like that that, I'd recommend you use something more robust like [Superstatic](https://github.com/firebase/superstatic).

**Comment by nsisodiya** [comment]
@scottcorgan  I have solved my problem by using Grunt - https://github.com/nsisodiya/react-kit/blob/a26b0050085587b42a0a02d80d63b62931615421/Gruntfile.js 
PushState + LiveReload using Grunt file
