### ISSUE TITLE
path "img/me.jpg" serves index.html, not image

### ISSUE THREAD

**Issue by hnag409** [scottcorgan/pushstate-server#18]
changing the file name to something other than `me.jpg` fixes this particular instance.

**Comment by euwest** [comment]
can you share (some of) your source code? it's working fine for me.

**Comment by scottcorgan** [comment]
@hnag409 is still an issue?

**Comment by scottcorgan** [comment]
Should be fixed by https://github.com/scottcorgan/pushstate-server/commit/d338323c3f5995a5b4f01b311faaaa097779dba0
