### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by vicMasons** [scottcorgan/pushstate-server#20]
Is there cors support, how would I add it?

**Comment by scottcorgan** [comment]
What's your use case for cors?

**Comment by vicMasons** [comment]
Using ajax to load html. pushserve project does cors, it's just a header
you return.

**Comment by scottcorgan** [comment]
Honestly, this was meant to just be a simple way to server index.html for all routes. I'd recommend something like https://github.com/firebase/superstatic for more complex routing. It's more reliable and very configurable.

It's what Firebase hosting uses in production!
