### ISSUE TITLE
Bind an address

### ISSUE THREAD

**Issue by williamle8300** [scottcorgan/pushstate-server#22]
Is there a way to bind an address besides `localhost`?

I want to use this in a production website using a public ip.

**Comment by scottcorgan** [comment]
There isn't a way currently, but I'd be open to a PR to add that functionality!

**Comment by williamle8300** [comment]
Aw darn. I don't have the technical chops to implement this feature.

**Comment by scottcorgan** [comment]
@williamle8300, check out https://github.com/firebase/superstatic

**Comment by zodiac** [comment]
AFAICT pushstate uses connect's app.listen (https://github.com/scottcorgan/pushstate-server/blob/8f830b382f0c1f4f63270b9f53655c48c44b7787/index.js#L33-L35) which binds to all addresses, not just local addresses

**Comment by allcentury** [comment]
It apparently does bind and works fine with docker.

```
docker run -p 9000:9000 my_image
Listening on port 9000 (http://localhost:9000)
```

**Comment by williamle8300** [comment]
Bind an address--not port

**Comment by allcentury** [comment]
Ya, it's binding to `0.0.0.0` here - otherwise I wouldn't be able to access 9000 via localhost.

**Comment by williamle8300** [comment]
Can you bind to a different address though?

(BTW localhost is 127.0.0.1 not 0.0.0.0)

**Comment by allcentury** [comment]
Yes, localhost is 127.0.0.1.  The application in the container on the other hand is not localhost unless I can bind it to accept all traffic (which is what I'm describing above).  Anyways, just pushed up a PR to allow binding across IP's.
