### ISSUE TITLE
Gzip compression

### ISSUE THREAD

**Issue by bensleveritt** [scottcorgan/pushstate-server#50]
Is there any way to turn Gzip on? I'm using `pushstate-server` cli to test final build sizes for a react app, and it'd be good to know if gzipping will help reduce the sizes significantly.

**Comment by scottcorgan** [comment]
There is a default compression set to gzip your responses https://github.com/scottcorgan/pushstate-server/blob/master/index.js#L25.

Is there something that indicates otherwise?

**Comment by bensleveritt** [comment]
Ah, I'm sorry. It's a misunderstanding on my part. I was looking at Woff/Woff2 files and of course they're already compressed.

Nevermind.

(Thanks for the quick response tho)
