### ISSUE TITLE
Serving a subdirectory's separate index.html

### ISSUE THREAD

**Issue by Quas94** [scottcorgan/pushstate-server#69]
I'm trying to serve two apps under one domain; one at the root (example.com/) and the other in the next level directory (example.com/abc).

I want all routes to serve example.com/index.html, with the exception of example.com/abc and its subroutes which should serve example.com/abc/index.html

How should I approach this? Thanks

**Comment by scottcorgan** [comment]
That may be out of the scope of this package. You might want to try something like https://github.com/firebase/superstatic#configuration. Specifically look at the `rewrites` section.
