### ISSUE TITLE
how to run server if I have install pushstate-server globally

### ISSUE THREAD

**Issue by chandan7193** [scottcorgan/pushstate-server#70]
'''
pushstate-server ['./build'] [5001]
'''
I have entered this command on cmd and it gives message
'''
Listening on port undefined (http://undefined:undefined)
'''

**Comment by scottcorgan** [comment]
Try `pushstate-server ./build 5001`. The `[..]` (brackets) on the readme are there to denote that it's optional. Sorry about that.

**Comment by chandan7193** [comment]
Thanks it worked properly.
