### ISSUE TITLE
Command line usage is incorrect with v3.1.0

### ISSUE THREAD

**Issue by wyze** [scottcorgan/pushstate-server#84]
I came across this because our docker images stopped serving files correctly. Our command is `pushstate-server ./dist 8080` which worked fine in 3.0.1, but after getting 3.1.0 it uses the default port (9000) instead of 8080.

Just thought I'd log an issue here so readme could be updated or changes could be made to bring back that functionality.

**Comment by janhartmann** [comment]
This just broke our builds. Please update the docs.

**Comment by scottcorgan** [comment]
This is accidentally a breaking change. Sorry about that. Which port would you prefer?

**Comment by janhartmann** [comment]
I would prefer specifying it, just like the previous version:

pushstate-server ./ 5000

But this will mount on 9000 in v3.1.0

**Comment by weichengcheng** [comment]
The original command is unavailable. Please update the docs.

**Comment by blocka** [comment]
I'm gonna guess this is a regression in minimist? It seems the only thing that changed is that you now have to specify the options directly 

```
pushstate-server -d ./dist -p 8080
```

**Comment by blocka** [comment]
or maybe it's all been broken since this commit: https://github.com/scottcorgan/pushstate-server/commit/0e07d439a8a5ec3141e780d38902cc32401ffe48#diff-a9b3224c7bedc40cad54b9dfab96553e

**Comment by wyze** [comment]
Looks like readme has been updated with #85.
